### ISSUE TITLE
Section on LLM evaluation tools

### ISSUE THREAD

**Issue by shrjain1312** [Hannibal046/Awesome-LLM#105]
Can you add a section on some eval tools, that would be really helpful

**Comment by Hannibal046** [comment]
Thanks for your suggestion! I would update this section soon. For now, you could refer to:
- [lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness)
- [OLMo-Eval](https://github.com/allenai/OLMo-Eval)
- [open-instruct](https://github.com/allenai/open-instruct/tree/main/eval)
- [llm_judge](https://github.com/lm-sys/FastChat/tree/main/fastchat/llm_judge)
- [cot-hub](https://github.com/FranxYao/chain-of-thought-hub)
