### ISSUE TITLE
Cohere's models not on the list.

### ISSUE THREAD

**Issue by pproulx4** [Hannibal046/Awesome-LLM#122]
Not sure if there's a requirement for truly open licencing to be on the list you have curated here, but Cohere's [Command-R](https://huggingface.co/CohereForAI/c4ai-command-r-v01) and [Command-R+](https://huggingface.co/CohereForAI/c4ai-command-r-plus) probably deserve to be on it.

**Comment by Hannibal046** [comment]
Sure! Welcome PR!
