### ISSUE TITLE
Doubt: add a new "other papers"

### ISSUE THREAD

**Issue by leomaurodesenv** [Hannibal046/Awesome-LLM#30]
I would like to contribute with this paper, but I do not know for sure which section fits better.
- It is a Big Data Architecture for Question Answering systems
- https://doi.org/10.5220/0011842700003467

**Comment by leomaurodesenv** [comment]
This paper proposes a new Big Data software reference architecture for implementing Question Answering systems. By Question Answering, we mean any natural language model that answers questions, for example Large Language Models such as ChatGPT.

In this article, we use RoBERTa as Question Answering and we intend to use ChatGPT in the next version. But this architecture is model agnostic, you can use whatever you like. 😉

**Comment by Hannibal046** [comment]
Hi, thanks for clarifying. It seems to me currently this paper doesn't overlap much with LLM. I believe the next version with ChatGPT would be more relevant to this repository. Looking forward to it!
