### ISSUE TITLE
LLM for learning a code repo and answering questions about the code design architecture etc?

### ISSUE THREAD

**Issue by preveen-stack** [Hannibal046/Awesome-LLM#32]
Is there an LLM that we can download and install on the local system which will go through a code repo and can answer question about the architecture and design of the code. Like for eg: snap from chatgpt
<img width="592" alt="image" src="https://github.com/Hannibal046/Awesome-LLM/assets/31464911/c5602bf2-89c8-4876-b0b7-f940a8f5fa8a">

**Comment by Hannibal046** [comment]
I believe this would help: 
- https://gpt-index.readthedocs.io/en/latest/
- https://python.langchain.com/en/latest/

**Comment by Hannibal046** [comment]
Also, hope this would also help. 
https://github.com/imartinez/privateGPT
