### ISSUE TITLE
Job opportunity

### ISSUE THREAD

**Issue by Acti0nJack87** [Hannibal046/Awesome-LLM#33]
Hi Hannibal,
My apologies for contacting you through your opensource project, but this is one method we use when headhunting exceptional talents on behalf of our clients within AI. I took a look through your work, and I am very impressed.

We are partnered with a US startup called Play.ht who have developed advanced text to speech technology to generate human grade AI voices from text in rapid time. After an incredibly successful launch they have over 7000 customers from small startups to enterprise level multinationals including SalesForce, Samsung and Verizon, content creators and video editors who can make use of 800 voices across 60 languages.

The three major use cases for their voice technology are video editing & voice cloning for post production edits, voiceovers for YouTube and video content, e-learning and training, IVR systems and audio accessibility. The platform decreases time for recording and updating and cost. Hiring voice actors is expensive and future editing is limited.

They are looking to scale their Engineering and Research team with Senior to principal level hires to build large generative LLM based models, end to end. You will be fully hands on building, training and deploying advanced voice models and deliver a human grade, context understanding speech product across two product areas, a library of over 100 ready to use voices and a text to voice editor API. To be successful in this role you will have previous experience building and training large generative models to deployment in a production setting at scale. Any experience in the TTS/ Voice space is a big plus but not essential.

In return you can expect a strong comp package including meaningful equity and a strong salary. You will also be one of the early team, responsible for bringing some of the most advanced and realistic voice products to market to be deployed across a number of industries and used worldwide.

This position can be fully remote, anywhere in the world, and you will work with a small, but rapidly scaling international team of world class engineers and developers.

Please can you let me know if you and I can organise a time to speak?
Here is a link to my LinkedIn profile - https://www.linkedin.com/in/jackdev/
And here is a link to my calendar - https://calendly.com/jackcubiq/20min

**Comment by Hannibal046** [comment]
Thanks for reaching me. I'm truly flattered. But I am currently ready to pursuing a doctoral degree, so I am afraid I don't have much time for this job opportunity. Thanks anyway!

**Comment by Acti0nJack87** [comment]
No problem at all, and thank you for letting me know.
Best of look in your PhD.
Do you have a LinkedIn profile? We could connect for future reference.

**Comment by Hannibal046** [comment]
You could always find me here :)
