### ISSUE TITLE
Could you add a paper in the section of Applications of LLM?

### ISSUE THREAD

**Issue by qiuhuachuan** [Hannibal046/Awesome-LLM#50]
paper title: SMILE: Single-turn to Multi-turn Inclusive Language Expansion via ChatGPT for Mental Health Support
paper link: https://arxiv.org/pdf/2305.00450.pdf
code repo: https://github.com/qiuhuachuan/smile

**Comment by Hannibal046** [comment]
Sure! Thanks for the great work
