### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Hanlian1** [Hannibal046/Awesome-LLM#6]
您好，我从https://github.com/yixinL7/SimCLS看到您问yixinL7的问题，我在跑SimCLS这个模型时遇到一些错误；
错误;RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
![图片](https://user-images.githubusercontent.com/123652717/220361921-018db4bc-5ffa-4bed-9989-acf8fea7cb80.png)

请问您知道这个是什么问题嘛？希望您有空的时候可以帮我看看，万分感激！

**Comment by Hannibal046** [comment]
你好,我没有碰到过类似的问题.看起来似乎是pytorch和cuda的版本不对,你可以切换到cpu试试.另外,请到SimCLS的repository提问相关问题,谢谢!
