### ISSUE TITLE
our recent survey may be suitable for "Instruction-Tuning" & "LLM-Alignment"

### ISSUE THREAD

**Issue by GaryYufei** [Hannibal046/Awesome-LLM#65]
Hi,

our recent survey [Aligning Large Language Models with Human: A Survey](https://arxiv.org/abs/2307.12966) may be a good fit for your planned section "Instruction-Tuning" & "LLM-Alignment".

Let me know your thoughts on this!

**Comment by Hannibal046** [comment]
Hi,
Indeed, this is a great comprehensive review paper with accompanying github repo. I would add this the Awesome-LLM soon.
Thanks so much!

**Comment by GaryYufei** [comment]
Any updates?

**Comment by Hannibal046** [comment]
Done
