### ISSUE TITLE
Logarithm Math for Neural Nets

### ISSUE THREAD

**Issue by Matrixbear29** [Hannibal046/Awesome-LLM#66]
Suggestion for LLM neural net model speedup which is very easy to achieve, will VASTLY speed up processing and the end result will basically be identical. LOGARITHMIC MATH.

Refer to the MATHOLOGER video on ANTI-SHAPESHIFTERS.

Simply put, in neural net matrixes, there are endless multiplication and divide functions. However in LOGARITHMIC math, LOG(X)+LOG(Y)=LOG(X * Y).
Likewise, LOG(X)-LOG(Y)=LOG(X / Y).

So, how to take advantage of these speedups?
If your neural net matrix is Algebraic in format, you convert the values to the LOG(X) value. Then all the multiply & divide math becomes addition and subtraction which uses considerably less processing. The end calculation result is in LOG(X) format, so you convert it back into Algebraic format by using the inverse logarithm routine. The matrix math as logarithm math will speed up everything by a factor of 10 per decimal point of accuracy (8 decimal points netting you a math speedup of 10000000 times the previous efforts using multiplication and division math).

**Comment by Hannibal046** [comment]
Hi, do you have some empirical results for this?

**Comment by zyrain** [comment]
https://arxiv.org/pdf/1910.09876.pdf
