### ISSUE TITLE
Open source UIs/webapps for LLM chatbots

### ISSUE THREAD

**Issue by clharman** [Hannibal046/Awesome-LLM#77]
Hello, great list, thanks for maintaining.

Felt this might be helpful to include:

https://github.com/snowfort-ai/awesome-llm-webapps

Collection of high quality, open source webapps to use as a starting point for LLM chatbots, etc. Much faster to start from an app than to start from a framework! Not sure where it would fit on the page, though.

**Comment by Hannibal046** [comment]
Done! Thanks for awesome-llm-webapps!
