### ISSUE TITLE
LLM data repos

### ISSUE THREAD

**Issue by JaejinCho** [Hannibal046/Awesome-LLM#92]
https://github.com/Hannibal046/Awesome-LLM/blame/7e4bf169521e45f1209f826e7850fe0566ae6a05/README.md#L10

I found below two GitHub repositories regarding the LLM dataset:
https://github.com/Zjh-819/LLMDataHub
https://github.com/yaodongC/awesome-instruction-dataset

**Comment by Hannibal046** [comment]
Hi @JaejinCho , thanks so much for introducing these two repos! Do you have any interest to make a PR for this?
