### ISSUE TITLE
ai00_rwkv_server

### ISSUE THREAD

**Issue by cgisky1980** [Hannibal046/Awesome-LLM#94]
AI00 RWKV Server is an inference API server based on the [RWKV model](https://github.com/BlinkDL/ChatRWKV).

It supports VULKAN/DX12/openGL parallel and concurrent batched inference and can run on all GPUs that support VULKAN/DX12/openGL. No need for Nvidia cards!!! AMD cards and even integrated graphics can be accelerated!!!

No need for bulky pytorch, CUDA and other runtime environments, it's compact and ready to use out of the box!

Compatible with OpenAI's ChatGPT API interface.

100% open source and commercially usable, under the MIT license.

If you are looking for a fast, efficient, and easy-to-use LLM API server, then AI00 RWKV Server is your best choice. It can be used for various tasks, including chatbots, text generation, translation, and Q&A.

https://github.com/cgisky1980/ai00_rwkv_server

**Comment by Hannibal046** [comment]
closed as no vote
